name: cluster_plot_pool
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda-forge::numpy=1.18.4
  - conda-forge::pandas=1.0.3
  - conda-forge::matplotlib=3.2.1
  - anaconda::requests=2.23.0
